"""initial_schema

Revision ID: 51fdb1b7e879
Revises:
Create Date: 2026-04-21 22:52:10.049199

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "51fdb1b7e879"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "empresa",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("nome_fantasia", sa.String(length=150), nullable=False),
        sa.Column("cnpj", sa.String(length=18), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_empresa")),
        sa.UniqueConstraint("cnpj", name=op.f("uq_empresa_cnpj")),
    )
    op.create_table(
        "usuario",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("empresa_id", sa.Integer(), nullable=False),
        sa.Column("nome_completo", sa.String(length=150), nullable=False),
        sa.Column("email_corporativo", sa.String(length=255), nullable=False),
        sa.Column("cargo", sa.String(length=120), nullable=False),
        sa.Column("senha_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["empresa_id"], ["empresa.id"], name=op.f("fk_usuario_empresa_id_empresa")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_usuario")),
    )
    op.create_index(
        op.f("ix_usuario_email_corporativo"),
        "usuario",
        ["email_corporativo"],
        unique=True,
    )
    op.create_index(
        op.f("ix_usuario_empresa_id"), "usuario", ["empresa_id"], unique=False
    )
    op.create_table(
        "chamado_psicologico",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("usuario_id", sa.Integer(), nullable=False),
        sa.Column(
            "data_hora",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("mensagem_opcional", sa.Text(), nullable=True),
        sa.Column(
            "status_envio",
            sa.String(length=20),
            server_default="pendente",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status_envio IN ('pendente', 'enviado', 'erro')",
            name=op.f("ck_chamado_psicologico_status_envio_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["usuario_id"],
            ["usuario.id"],
            name=op.f("fk_chamado_psicologico_usuario_id_usuario"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chamado_psicologico")),
    )
    op.create_index(
        op.f("ix_chamado_psicologico_usuario_id"),
        "chamado_psicologico",
        ["usuario_id"],
        unique=False,
    )
    op.create_table(
        "check_in",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("usuario_id", sa.Integer(), nullable=False),
        sa.Column(
            "data_hora",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("humor_geral", sa.String(length=50), nullable=False),
        sa.Column("respostas_json", sa.JSON(), nullable=False),
        sa.Column("nivel_estresse", sa.Integer(), nullable=False),
        sa.Column("insights_ia", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "nivel_estresse >= 0 AND nivel_estresse <= 100",
            name=op.f("ck_check_in_nivel_estresse_range"),
        ),
        sa.ForeignKeyConstraint(
            ["usuario_id"], ["usuario.id"], name=op.f("fk_check_in_usuario_id_usuario")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_check_in")),
    )
    op.create_index(
        op.f("ix_check_in_usuario_id"), "check_in", ["usuario_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_check_in_usuario_id"), table_name="check_in")
    op.drop_table("check_in")
    op.drop_index(
        op.f("ix_chamado_psicologico_usuario_id"), table_name="chamado_psicologico"
    )
    op.drop_table("chamado_psicologico")
    op.drop_index(op.f("ix_usuario_empresa_id"), table_name="usuario")
    op.drop_index(op.f("ix_usuario_email_corporativo"), table_name="usuario")
    op.drop_table("usuario")
    op.drop_table("empresa")
    # ### end Alembic commands ###
